### ISSUE TITLE
Fatal error: Call to a member function getLast() on a non-object

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Signal#2]
Was playing with Aura.Signal 

Error : 

Fatal error: Call to a member function getLast() on a non-object 

Fix : return results collection object for the `send()` and `process()` not returning anything .

Another Qn is :

In constructor itself we are cloning the result collection `$this->results = clone $this->result_collection;` , then why we need it in `send()` method again ?

```
// In Aura/Signal/Manager

public function send($origin, $signal)
{
    // clone a new result collection
    $this->results = clone $this->result_collection;

    // get the arguments to be passed to the handler
    $args = func_get_args();
    array_shift($args);
    array_shift($args);

    // now process the signal through the handlers
    $this->process($origin, $signal, $args);
    //return the result collection .
    return $this->results ;
}
```

Below is code that I was playing 

```
<?php
use Aura\Signal\Manager as SignalManager;

class Example
{
    protected $signal;

    public function __construct(SignalManager $signal)
    {
        $this->signal = $signal;
    }

    public function doSomething($text)
    {
        echo __METHOD__ . "<br/>";
        $results = $this->signal->send($this, 'example_signal', $text);
        /*
        $results = $this->signal->getResults();
        // go through each result ...
        foreach ($results as $result) {
            // ... and echo the value returned by the Handler callback
            //echo "<br /> The object that sent the signal. " . $result->origin;
            echo "<br /> The sender expected by the Handler. " . $result->sender;
            echo "<br /> The signal that was sent by the origin. " . $result->signal;
            echo "<br /> The value returned by the Handler callback. " . $result->value;
        }
         * 
         */
        $result = $results->getLast();
        echo "<br /> The signal that was sent by the origin. " . $result->signal;
        echo "<br /> The value returned by the Handler callback. " . $result->value;
    }
}

class ExampleOther
{
    protected $signal;

    public function __construct(SignalManager $signal)
    {
        $this->signal = $signal;
    }

    public function doSomethingElse($text)
    {
        echo __METHOD__ . "<br/>";
        $this->signal->send($this, 'example_signal', $text);
    }
}

$signal = require_once __DIR__ . '/Aura.Signal/scripts/instance.php';
$signal->handler(
    '*',
    'example_signal',
    function ($arg ) { 
        echo " example_signal Called " . $arg; 
    }
);

$closure = function() { 
    echo "Before all others. <br />"; 
    return " From Signal 1000";     
};
$signal->handler('Example', 'example_signal', $closure, 1000);

// add a closure at position 9000, which means it will be processed
// after all handlers at the default position 5000.
$closure = function() { 
    echo "<br /> After all others. <br />"; 
    return " From signal closure of value 6000";
};
$signal->handler('Example', 'example_signal', $closure, 6000);

$eg1 = new Example( $signal );
$eg1->doSomething('Hello World');

//$eg2 = new ExampleOther( $signal );
//$eg2->doSomethingElse('Hello World');
```

**Comment by harikt** [comment]
Pull request initialized .

https://github.com/auraphp/Aura.Signal/pull/3

**Comment by pmjones** [comment]
Hey man, can you attach a test case for this?

**Comment by harikt** [comment]
@pmjones also I guess that pull request was too old, so we may want to test the same again.
I will try to write a test case. But I may want your help, lets discuss tonight at irc if I didn't finish it :) .

**Comment by harikt** [comment]
@pmjones See https://github.com/auraphp/Aura.Signal/blob/master/src/Aura/Signal/Manager.php#L185 , you have already mentioned about the return type `ResultCollection` The results from each of the Handler objects. 
But forgot to return it . So in the above example the results is not having an object of it, hence the error and ie the pull request https://github.com/auraphp/Aura.Signal/pull/3 .

About the test case , I wonder for which one we neeed . About the clone one ?

**Comment by harikt** [comment]
Another Question is regarding the use of 

```
// clone a new result collection
$this->results = clone $this->result_collection;
```

in send() , do we need it in constructor then ?

```
$this->results = clone $this->result_collection;
```

**Comment by pmjones** [comment]
I don't think so; the idea is that the manager will have to deal with lots of send()ing, and it's easiest to reuse a clone of the initial empty collection.

**Comment by harikt** [comment]
ok for clone in send() . What about in constructor ? Or does that answers all ?

**Comment by pmjones** [comment]
The constructor already has a ResultCollection param.  Am I missing what you're getting at?

**Comment by harikt** [comment]
My query is regarding https://github.com/auraphp/Aura.Signal/blob/master/src/Aura/Signal/Manager.php#L114 . Do we need that there for we already have the clone in send() .

**Comment by pmjones** [comment]
But we also have getResults(), which needs to return a ResultCollection, even if you haven't called send() yet.

**Comment by harikt** [comment]
Yup that make sense :) . Sorry for the long conversation :D .
